#
# Copyright © 2011 - 2013 Aaron Mahan.
# Copyright © 2013 - 2016 Forerunner Games, LLC.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

sudo: false
install: true
language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23

before_install:
  - pip install --user s3cmd
  - export PATH=$PATH:$HOME/.local/bin

script:
  - ./gradlew clean build integrationTest

after_success:
  - ./gradlew desktop:dist server:dist
  - ./scripts/travis-collect-upload-build-artifacts.sh
  - ./scripts/travis-create-upload-last-successful-build-number.sh
  - ./scripts/travis-collect-upload-assets.sh

after_failure:
  - ./scripts/travis-collect-upload-build-artifacts.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - developers@forerunnergames.com
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: dywelOlZoAuVoFEY3ZwRLgetKP+BWxAz1cX9kWUF14oUeETSoK+lAshCK1JhGBNKpJUjiFnhd4IiRtnYfN8jdTCOojgHU63Iff6yMyibUTLX/joOR583N/DOpn5SpE74qfsNWKv6FxjeodmL8rfPInj7SDI7mHULYN1EHmfDM1BShaOdfDOI4jdnTKXeDsNJt3FPUEURUVo5qAmJpHgVxFBym5GLDVaH4SOA21PZnhPRcNzXx0KowM2+x+4LqfMzno+MZkMla1f5F3+MLlLG7np78rGJ8laWKcUzZDiiWuSrsAtg1jnPfq2KCv1Ajnn34+43rEQXcp7Ss7oTMHK6tDEZhHHPSjjq4HVvHKNqN6YRcf4T1EozbtuThOiwbUv5UhQLwPRQf+OJMvCsVvhsyB8Yg/gttpu2zTbOLnWG79JkVIob2HTm+dxBACWugsk4ScmhRd7niQvb8ESIQzWUB8Q4dOYprU9hT7xBTVJ1Aj+4qFz2ZE2+tbj8EnMMN4hnjKgfQGcLFUkuok3H6s87dTdn9h6oB4YfYUH8WSjN9AVzMq5tMn3IzyRraARh+WVP3V67n9bXmph5tgJpcBIPs1v1bY8gOlIFFhajh4W7PuJ7+Npw5bHC3nMkoFh0MWIBJdchIv4UGA57PhejzrR0YBmdQk+KoqJiep/luI9HlDM=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html

env:
  global:
    - secure: hJGlGp4bz8nq6DEr5Qa6rTM7yNt8HuawMdwarX132iNetpuPohKEMnIj9WSqkcH0rLyosj6AQVAJqTXEJ5WcRKyfSYnp8EVAHr2RsVak+qSCvZAhJeMq+do41CI29LBxb40ygW4rB7McDkLmlN+WlFK5DCD1TPyvexg0OUoegq3sAKSO2MmXaydbCDutrt5tkx67YEt1viwfd+iheINZX1ZxalrqCtKeun0+yVwRrdL/jjf/HjexWwtigDq3WKOzerj1UuGuey6XWNMikBmbDIxMDjg8HY3xOfkTiaJ9Q1ou+EVk+a2f/bc+32dMaxeuGnEXh5R7M6wHTuUh1I6vur3ceqRbvw6DoVAJLTjkT7c4NS0C+DZ2qAUk9YEoSKv4vTioSPISii5sVfs8XDT8S1SSmY3tqRx9pg9gou6lWMJOjymz6OoiWgw2T30OvkOJ5Goc4pI28LzqZRykYdR8AOGQul+av0+GyHBijBXgPBComWoDaM9iSqQWcbmrJD4kECoOD1kE/J68RHCEXUYvRINlkFpefhcTg7ce0j1x5udyrCIZuhFXKLMj7M8hYFl4aitU25FqQFUin9+el00w0AUdZp3ZAQjF7fUJd3JareFJaE15Sx+pfNR4xPIxKS0i37YjFp4XYZbQgu0lTtpNgri3uGNct2bXfTtTyedRr7g=
    - secure: 1Pm5SbrQrzLZuSv0CoU0wdI0Gnyt3GDbTHzie087Be/dtOBPmNDTHx1xEtCFziWWiS+8YvASSuJ1ZhLRWvqxtC0S2lQ9ENyDeUULX9RYoAqHnArpYR5QAWHHM3xEiIjG7fKQTknpvI+RbXW122JKxWgsmsR3argWXvgJvsgfyavwq245RB3lG0AXLqOGk+VL5w4IaBE8E1B2iU9wRe0gA4pNbWaF61uiSFo/J8/lt89STA9WDeCdEQ3swdsd2L7/FPpujb5tpmjCpZS69xF/jGkUG5YiEZ9jx5a6kDcJ/SLt4BBDgd9aBxVBigW16PW/yZd+VU6T7PnHBnosgmzFJkauMp2OyW9DDzezveXs/xbEkSXJ2hgueKHULX7DvM/TIXPZio1X9/29pJ3LbMUjWnLXuFVf8Xfi3NEmc+TyJECWJqokaPIcP0WobLgtpqkGcbcMRBnxPNh/H0R+zssAj1ZlewOiGwZN/rCpncXfn4vtwessdNRV6MEaq/0/QRJfMlMPimZw5EFzozMhM76TlU+ycAmWpDx94Z2djz1kk4JQiKXIfFc5g6VmMCn43aE8QxlgfGgHNTsGY1fFT2aADJDSOC4y1/G8oAeicdyuDMV8M2wMVUopqumFRYli02BI2zMZVX+41eD9kPEzBWadFiaOUdQapjROk6SCzWkv2JU=
