#
# Copyright © 2011 - 2013 Aaron Mahan.
# Copyright © 2013 - 2016 Forerunner Games, LLC.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

sudo: false
install: true
language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - ./gradlew clean build integrationTest

after_success:
  - ./gradlew desktop:dist server:dist
  - ./scripts/travis-collect-upload-build-artifacts.sh
  - ./scripts/travis-create-upload-last-successful-build-number.sh
  - ./scripts/travis-collect-upload-assets.sh

after_failure:
  - ./scripts/travis-collect-upload-build-artifacts.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - developers@forerunnergames.com
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: dywelOlZoAuVoFEY3ZwRLgetKP+BWxAz1cX9kWUF14oUeETSoK+lAshCK1JhGBNKpJUjiFnhd4IiRtnYfN8jdTCOojgHU63Iff6yMyibUTLX/joOR583N/DOpn5SpE74qfsNWKv6FxjeodmL8rfPInj7SDI7mHULYN1EHmfDM1BShaOdfDOI4jdnTKXeDsNJt3FPUEURUVo5qAmJpHgVxFBym5GLDVaH4SOA21PZnhPRcNzXx0KowM2+x+4LqfMzno+MZkMla1f5F3+MLlLG7np78rGJ8laWKcUzZDiiWuSrsAtg1jnPfq2KCv1Ajnn34+43rEQXcp7Ss7oTMHK6tDEZhHHPSjjq4HVvHKNqN6YRcf4T1EozbtuThOiwbUv5UhQLwPRQf+OJMvCsVvhsyB8Yg/gttpu2zTbOLnWG79JkVIob2HTm+dxBACWugsk4ScmhRd7niQvb8ESIQzWUB8Q4dOYprU9hT7xBTVJ1Aj+4qFz2ZE2+tbj8EnMMN4hnjKgfQGcLFUkuok3H6s87dTdn9h6oB4YfYUH8WSjN9AVzMq5tMn3IzyRraARh+WVP3V67n9bXmph5tgJpcBIPs1v1bY8gOlIFFhajh4W7PuJ7+Npw5bHC3nMkoFh0MWIBJdchIv4UGA57PhejzrR0YBmdQk+KoqJiep/luI9HlDM=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html

env:
  global:
    - secure: QTdaI4D+LqaMUhCTohJAZ7QGDI+pzI9LWvy+qdGFNY8VmayoMNZksKWjQomubu9KeC87bxUXFrJReRX/ACEcWzGX10MGiDHFMwZ3FwUyUH95k46oxlMaLsAlLEljaIeUnpWExG8gKjCQIcoQbOYYyvB774CUlJNyX5XWKX9O1lbKDaKsW0gWNFREyOZUJBNuwn/44DjPBISK8xPxk+ztzT6tRlbkllNgyVHQlAjxeH4TKkFlLN2sJfo3L8bfDbHhpKoukDacaueAa/wW88r+ttyDM00FKtV7U1kC6jmWjXlj3P2jEK2QorFdCsnuiyesLEg85YLECSSvLZQuVZKgt0jKFsaDkkoYcd8eD9T2dz4EyhIHfzdAj+tnJ1xJ+hWRxskQBOPPUtAE99bzR/cWgM7xeUfNdGRR+YNPbLa1KjXkb298zwgAjoMSMTl2Qkt00HhXL7Wi9+MVB1oYeALDWYwIQKueaXaDOt0VpfQlWHLipYBV06UYOTYvy8pwYOp4OjaYX10H/57rwc5ywySMShFYm72ovAyR3dl1Si1q2Fwn7bNzWtsxjSpA1zCt8u08e6ZLkgAsPWUVY2Fpf85TYlij8msox1MlTNCqOuXZ7Ikr/HGoRddULdZqECQIHFqcF6PyfAvK6cIog/0ZnXDq1Z5o08MX0sHVSgKDsGX7mOI=
    - secure: XHp41JmSa4YUCUytJ+SKqAXTS1hiGbapvMVtOcEHsB1Q9yV/POKwsNCedY5ERd39fy1M35wKTjbHiZBqjOw9UhqAbu6ljf9b8ROhNirpkg1ASRIF1BSNtLEH1yyS0LDgla5urjEj56HCNOU6TeEdKP3ZywtwukSwiQR1+VN7sbab5cyJ/mmkXKwLvd9iApllH8747BIJ7TYj0nNab0xaPF2UqBmCSrpGrJrWsg4SSc1krZFBFk2ve44bwwNPi/QAT1nExxtj3juSy3B2upQVnAzJNNShlSpLZOh5c3I2WMiQYc7ffbR513FXIiAljPFq0diuWdUnfqCHQAfwKA2h2X12Ep+h3xV5XpHJ0hzpqNSe+Fyl9Nm2YbyijHPkGVlOja8Vhyrzj9HcSXwoCLxoroAvZjmkNUIryd1f1vY5T9zpOO68AKfh5kairFMumYLC5yBjgr3LdGOPBQfn7ofhZHSrb1a4wBK7CE/L+Uo48vX4EREhyHcwTxw9O252kNl6bbkVgmoAYAYKui+Dh2NriKuVqIYOddAXiEwlnqLRq4DFxwGUTc+H3AdPoS5QC1Bmq8OzwfQTUJaOariikmfB8AMSdeJcw+PJJlfbtZ+2gW1TjCM9oG9nLqepF2buZlfhJWLOJ+UEEeQEL0xhQlB9L43dATz6SGD7j96KE2r9WDY=
