sudo: false
install: true
language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23

addons:
  artifacts:
    debug: true
    branch: develop
    bucket: ci.forerunnergames.com
    target_paths: builds/peril/$TRAVIS_BUILD_NUMBER
    paths:
      - $(find -type d -name 'build' | tr "\n" ":")
    key:
      secure: hZ5E0PwO+qB0sVFl9PhCE6RsTJAhTZarjlusBO2G7Xrn72QklBsST9mcv3GeWG4SrNPU3I90yIWpaklW4WH7wPzh+kHk0viq/sLihEIjm8GNPkUJ6VUOjHvfz9XMOgGZFGOI03BKYpi1NO16iwRfNoFmak5gECeq33HpLbL3fENgRVf9esOevqkxySiz1kWJSPw9JkRPD7aCCJwPVbpTe5SWNWuCUaJPrURps5tUQOnqetaTIr2wBucRYY+M0XS0WF7f9JKEMt6uh7U4rTpMyzKM8m6TvE6q2rqcDUAE/5TKP742tfUYOGyVQOidtZ8kDGDFlBA35mLaFEw5qIFTofl+b213xOcXfjuKCX/k+/EwUfNuxPwW4HdAa/Eq4HF2TvuCTNVHPBXTvFMovtBvWg1Q6iNf61m7gIYWvbSEhsmmAzXOCPxG6Q+2pmyotTnh43d3BrjKMuHZtE3vjFcoQgmrLbFGFIYaMPVb4lGGwI7jeHnwBbWlscTwXTssVfCOvrVp50WUPWiA1Lz7orAYVGQyhatKzvH6Ds0/rU4zOBz9c22QgLpN3BEPn6dVt9ottQ55ng1dWahkYQKt+BicAosYFcpneo5ndO33QKVm3G6badv4X1zWe8cbbjfdkXyNOqonxzWFZi7+QXe9eOqnjzDD6Z+KlqGxBdshnbvAmNM=
    secret:
      secure: ZEnfKsL9We7tPFV41O7itfg/uH0TynhdLgqLKC9B24NQTFQimI+curiqUU5XrDNGiDuel0zU7CNfcbrmKgW6Mp/9PwOkGusJSFJup/5qMmPwfmGaSc0CqR03l6LpdZE44ZfkAY8qZvyJwSV/AUpeimYGL2mzn+/jpv5sE9tGLKH1mYMjk+KtJTdbG6zXeJr1pHVfpZ4XiNxmSHhMBHW77ZV6dk7iA3riAQb4g5EUL00uJwr7MiezjrRJv0VzOUCqofFZCNcAn5HPWpu9icAvjSjTeqA+Uo3Bnaihj9igqNS50OuP8M4xG4/2dx38zvV61yZp/COHU1FAdyQMD3Ksy36gfxg0E9bGOPD8O2oW8tPt9G69B9rjwpmS6IkE3izc1f5hfquyLO41ObEYQb2o0uCkRVAmb7OCphqNWIVp394YEqx4Ho9nDmoxVQKlvyCzC5yMi4pdWyTuDe4dzDd/Co1G3sPYuCXUZd3lPDZleWamxzn0oskQY9TF+wozk8RViGGW8NkpMoOKfVJN0cWzpNxGvbpj6WCh2/Wwbxl682+DFweDew0/Pz5E5h9gQxknTlbeQPANfOCHTnRq+Ak1mNa8DextBbIAcpqP3dOWkTpTo4WgPmS0OZ1e0qY3O//uYoGI9ekNxokVvECqcVzmT3gnlltdKVuF1Mfp2uuDBdg=

script:
  - ./gradlew clean build integrationTest

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - developers@forerunnergames.com
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: dywelOlZoAuVoFEY3ZwRLgetKP+BWxAz1cX9kWUF14oUeETSoK+lAshCK1JhGBNKpJUjiFnhd4IiRtnYfN8jdTCOojgHU63Iff6yMyibUTLX/joOR583N/DOpn5SpE74qfsNWKv6FxjeodmL8rfPInj7SDI7mHULYN1EHmfDM1BShaOdfDOI4jdnTKXeDsNJt3FPUEURUVo5qAmJpHgVxFBym5GLDVaH4SOA21PZnhPRcNzXx0KowM2+x+4LqfMzno+MZkMla1f5F3+MLlLG7np78rGJ8laWKcUzZDiiWuSrsAtg1jnPfq2KCv1Ajnn34+43rEQXcp7Ss7oTMHK6tDEZhHHPSjjq4HVvHKNqN6YRcf4T1EozbtuThOiwbUv5UhQLwPRQf+OJMvCsVvhsyB8Yg/gttpu2zTbOLnWG79JkVIob2HTm+dxBACWugsk4ScmhRd7niQvb8ESIQzWUB8Q4dOYprU9hT7xBTVJ1Aj+4qFz2ZE2+tbj8EnMMN4hnjKgfQGcLFUkuok3H6s87dTdn9h6oB4YfYUH8WSjN9AVzMq5tMn3IzyRraARh+WVP3V67n9bXmph5tgJpcBIPs1v1bY8gOlIFFhajh4W7PuJ7+Npw5bHC3nMkoFh0MWIBJdchIv4UGA57PhejzrR0YBmdQk+KoqJiep/luI9HlDM=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
