sudo: false
install: true
language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23

script:
  - ./gradlew clean build integrationTest

after_success:
  - ./gradlew desktop:dist server:dist
  - ./collect-build-artifacts.sh

addons:
  artifacts:
    branch: develop
    bucket: ci.forerunnergames.com
    target_paths: builds/peril/$TRAVIS_BUILD_NUMBER
    paths: "build/uploaded"
    key:
      secure: GCV2uDqxf5VQZktdNxJfXAfXtaWGIjUKHn8jmVUveUq//R3rBcxcem1ggzCmWfxBVqUUTjSNaFq7BQtjeZtcOLfeaPgXP3FTCsCuPEfrld1UbA9CL5Cy0g1bfO31QtPwlzsZ7SWxuTb2QOeOMzws9sg/OnX/6lVUTtu5JITK+9MyKrvzL9Qk3azmzBojGml6VszLBddWkfSzsH/yp5307nho/b0One2L9Y73e6n4u470pdxj+3JheK7WviiqpZWsbqe0QYzxfbKQU/PmFYV392jCGAkjeTHINaLJVmsW4XgdSSP1ZGMaHgu2UqnxvgsSnW88MMnC20KITRJf4ru5Vn/XdSX9mP3oIxoVDrWLGMnCklaLwZ0Wl9ssE/xcObRwRumSvanGCwuRM3cqpyrcbxU99+Qj+TmNP7/uL8TzGlk5uMp0niQeLXDcAuJSuWlTkfFiBWN3uhgRf4x0Y04/kJBBa4ve2uYMdr7/9kFj3AKpCOBPVP4HPT8POHJHAfIYHwoo+xdxCX9ypKmsFd90+9IBrT60m4mZT2O5zj/7Vhu3d5BuU9uzu1FaFw7IgtaP9nEzw+zrtzfPEW3LqwuMubSkukTLsVFbNMJeDakZ7BolT4cz0N1m9K1JGf6sCYCCiRTsQ5HTCp7P5S81fPm5qq68mHLcp0WNBLuHXDg+hzA=
    secret:
      secure: xOAX0p2YOTgWh2YoQqGhLyEjLjmIGIUy32/5G2nRmoHcmLcLE6WB/xsCUpnaFm2UJPlx+mZravXz417aiSmIB7XEbM5YBs5/iGBgbHObLTXQ2wmzhHnFZvCk1537RPeRyNNTT3zJrbamGZn2lXHqfBV0DqIj1/4mIrkar1WjnfCJPI6Dfl96TywFxxbHAd8jXMgZfn17u6sUCOlQ4rmABFTiGS0wuaYnf7CelPs7KUUgI9cvpyB4VENNDPIjNRherEQm6kNTulsaYpARoUzHH4g9L3GDJPk9v3VgbgGLJzCcV8pM3Db728LQJbEAIbmhp7xOARw3IQen66I4JBehhNJYKtSVOoUBOwxmbrrAOADhiU7QwR9bq4ZTa2j0t27upLMt/PvparCDUBO4SRJ7939j1wiJBmtpOwFI78c2NfxE8SSzbHY9qcmbJZtoRQqEdxLXek3aoEd7S+z0zhJ5jrG/kXcFL7ldmiFJT97r5XNbdhRDE6zu534GsMDVxqNhAGoSEUGCeV1b4o44aYB9iPu+tNw6QkiVk9OTelSKefVd4xrh/eXkj84NQvGXkrfMZQJxmUPAWsj38uYyCM6XHDDT1kfr55/LB3aIonbA0n8Vh8MJm+5fRlRRcQiEMexk/w4cBjAjrtc5bR+LJXvbigh2SVMYzmEaaZznzSYHFfc=

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - developers@forerunnergames.com
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: dywelOlZoAuVoFEY3ZwRLgetKP+BWxAz1cX9kWUF14oUeETSoK+lAshCK1JhGBNKpJUjiFnhd4IiRtnYfN8jdTCOojgHU63Iff6yMyibUTLX/joOR583N/DOpn5SpE74qfsNWKv6FxjeodmL8rfPInj7SDI7mHULYN1EHmfDM1BShaOdfDOI4jdnTKXeDsNJt3FPUEURUVo5qAmJpHgVxFBym5GLDVaH4SOA21PZnhPRcNzXx0KowM2+x+4LqfMzno+MZkMla1f5F3+MLlLG7np78rGJ8laWKcUzZDiiWuSrsAtg1jnPfq2KCv1Ajnn34+43rEQXcp7Ss7oTMHK6tDEZhHHPSjjq4HVvHKNqN6YRcf4T1EozbtuThOiwbUv5UhQLwPRQf+OJMvCsVvhsyB8Yg/gttpu2zTbOLnWG79JkVIob2HTm+dxBACWugsk4ScmhRd7niQvb8ESIQzWUB8Q4dOYprU9hT7xBTVJ1Aj+4qFz2ZE2+tbj8EnMMN4hnjKgfQGcLFUkuok3H6s87dTdn9h6oB4YfYUH8WSjN9AVzMq5tMn3IzyRraARh+WVP3V67n9bXmph5tgJpcBIPs1v1bY8gOlIFFhajh4W7PuJ7+Npw5bHC3nMkoFh0MWIBJdchIv4UGA57PhejzrR0YBmdQk+KoqJiep/luI9HlDM=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
