sudo: false
install: true
language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23

addons:
  artifacts:
    debug: true
    branch: develop
    bucket: ci.forerunnergames.com
    target_paths: builds/peril/$TRAVIS_BUILD_NUMBER
    paths:
      - $(find -type d -name 'build' | tr "\n" ":")
    key:
      secure: pOQdkzFerSL88i0OtQWyX/4cOzxguhnZ4+sooi1aMyREriyA6Y9AErnXNiHVvii4KBbLv7T99TPNCeGOZb7b/mNvniFJrRs/rcmgG8/ogDWwTkHLttZ7ELJfZNjGQlimVzpYIf1RrOVuf7gny65+Ma0s8V3pQzA0gQhsuHP/wNb6rbbVA3ZNEiWg5xxsjif8Bcxvu1sC2SvhGdeMQF0x34kbxJ7WgLN/NZqSdc+80NHpy7CaE6PG02moO3yDZlMoQXP5PuWFUsD2FuZgmnfCnjagVY6Q0pb1/wPXtcd7/8bdgunY7FWa4xle+gkhkvJXV5axdwzGKX9aVBs+axTnKixejflm6oeAmKJfikunwqY0i1N5slqY5L4JRnONKDsTdV1lDjNbige8kKBrcP4mibmg6yDx+N8Fzz16pEVKDmixJzwz1/cWtLPUi87tEogkW4NniDNweVipeE1VJiZ24u8C+V5lTUq2DGytsXv7fvl8lMxY9Ysgn46sgnghWLZ5lZZSR2XNxK4/7BncmWgiDFbANPXeWgP+/AcWQLvixuX02f2VDIRMD6fuJQvoubZPxBjeqAG1+VaST0ZDVcmodXb6QANu5ibGYa8gDyG1lXeiUTxGQwL6E7qnJkBjohQodU4A46bQ5hRLyGjuio1Y0TvK8Et27XL8JSXAZUVNUH8=
    secret:
      secure: mREOvlnYUj+GuXHkZyPDCZNYyUo/U+rUM7pQKWjm+psHN63ywHFn+QEqFTKVQUu53gvxI23HG8qLM0/J9TJ0s2P7tqTbshRGalHVb08enLp2vRjwdcDnMX6hFFKrFjCkzueIWNbxQhvtWH796W6s9gfcCC52fKhbTonjXxtSPhC61bfMhiOxQ+0mu6NtDvddU4HSv30dkugNJuSlbqRsUmlL0Z18eAZcSUPm67ot9oZZVLAkKM7mGY8oeXjtvAYtoyNc7GlQPBep+D3qy3hZcExNanUhIJGIQNgv6xjzEpqMgOclwMmk/uar6ewPoziijNzHRes6yxg/iM6GNSdlu8ZeySpEJisDhaCw5MygyLfxO7HDbap798pOMGw/6PGBVaG+utm13iH68XqgcLW1TGvOvJgFyBrekJOgIeK25k6h7UMFIz14JX8mc2F8aQbzDxJWvIZPZ/UdXgwcfOJqZK7SG6HtV4jBzbELkjKIi7y5juofYZKEyLFmh3NZBQCSxUtDgXl0zQHM/MKLRwv9m/xJrdO79AiqmSYDg8nvCLsuePdReV61OpUV69ab4s/mBu0ZaJuTu30GkhNR8qYocBeNmCyhJUNOWaN7lVFRmTqUo3Vr0HVml0Amnsi+cTyGSQnxRsBLsnHsLeA1pmXnawwGHJGbjZHy9ICT8cY8ZIw=

script:
  - ./gradlew clean build integrationTest

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - developers@forerunnergames.com
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: dywelOlZoAuVoFEY3ZwRLgetKP+BWxAz1cX9kWUF14oUeETSoK+lAshCK1JhGBNKpJUjiFnhd4IiRtnYfN8jdTCOojgHU63Iff6yMyibUTLX/joOR583N/DOpn5SpE74qfsNWKv6FxjeodmL8rfPInj7SDI7mHULYN1EHmfDM1BShaOdfDOI4jdnTKXeDsNJt3FPUEURUVo5qAmJpHgVxFBym5GLDVaH4SOA21PZnhPRcNzXx0KowM2+x+4LqfMzno+MZkMla1f5F3+MLlLG7np78rGJ8laWKcUzZDiiWuSrsAtg1jnPfq2KCv1Ajnn34+43rEQXcp7Ss7oTMHK6tDEZhHHPSjjq4HVvHKNqN6YRcf4T1EozbtuThOiwbUv5UhQLwPRQf+OJMvCsVvhsyB8Yg/gttpu2zTbOLnWG79JkVIob2HTm+dxBACWugsk4ScmhRd7niQvb8ESIQzWUB8Q4dOYprU9hT7xBTVJ1Aj+4qFz2ZE2+tbj8EnMMN4hnjKgfQGcLFUkuok3H6s87dTdn9h6oB4YfYUH8WSjN9AVzMq5tMn3IzyRraARh+WVP3V67n9bXmph5tgJpcBIPs1v1bY8gOlIFFhajh4W7PuJ7+Npw5bHC3nMkoFh0MWIBJdchIv4UGA57PhejzrR0YBmdQk+KoqJiep/luI9HlDM=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
